import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Axios from "axios";
import ProductItem from "@/components/ProductItem";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

function Home({ productsData }) {
  // function Home() {

  console.log("productsData =", productsData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <h1 className="text-3xl font-bold underline">Hello world!</h1>

        <div className="grid grid-cols-3 gap-2">
          {React.Children.toArray(
            productsData.map((product) => {
              return <ProductItem product={product}></ProductItem>;
            })
          )}
        </div>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const data = await Axios.get("https://fakestoreapi.com/products");

  console.log("data", data);

  return {
    props: {
      productsData: data.data,
    },
  };
};

export default Home;
